name: PRUEBA_GITHUB_ACTIONS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  despliegue_en_servidor:
    runs-on: self-hosted

    steps:
      - name: Sincronización del repositorio
        run: echo "Se sincroniza el repositorio"

      - name: Instalación de dependencias
        run: echo "Instacion de la libreria"

      - name: Despliegue finalizado
        run: echo "Despligue listo :)"
